---
description: Pipeline for processing Kafka Raft metrics.
processors:
  - rename:
      field: jolokia.metrics
      target_field: kafka.raft
      ignore_missing: true
      ignore_failure: true
  - remove:
      field: jolokia
      ignore_missing: true
      ignore_failure: true
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
